{
 "title": "DataCore Overview V2.1",
 "description": "You can find all details to run it on GitHub https://github.com/lblanc/grafana-integration",
 "tags": [
  "DataCore_REST",
  "All Dashboards"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "DataCore_Servers",
    "label": "DataCore Servers",
    "query": "SHOW TAG VALUES WITH KEY = \"host\" WHERE \"objectname\" = 'DataCore Servers'"
   },
   {
    "name": "DataCore_Virtual_Disks",
    "label": "DataCore Virtual Disks",
    "query": "SHOW TAG VALUES WITH KEY = \"instance\" WHERE \"objectname\" = 'DataCore Virtual disks' and \"instance\" !~ /Logstore/"
   },
   {
    "name": "DataCore_Disk_pools",
    "label": "DataCore Disk Pools",
    "query": "SHOW TAG VALUES WITH KEY = \"instance\" WHERE \"objectname\" = 'DataCore Disk pools'"
   },
   {
    "name": "DataCore_Physical_Disks",
    "label": "DataCore Physical Disk",
    "query": "SHOW TAG VALUES WITH KEY = \"instance\" WHERE \"objectname\" = 'DataCore Physical disk' and \"Type\" = '4'"
   },
   {
    "name": "DataCore_SCSI_Ports",
    "label": "DataCore SCSI Ports",
    "query": "SHOW TAG VALUES WITH KEY = \"instance\" WHERE \"objectname\" = 'DataCore SCSI ports' and (\"PortRole\" = '1' or \"PortRole\" = '2' or \"PortRole\" = '4' )"
   }
  ]
 },
 "panels": [
  {
   "title": "DataCore Server: $DataCore_Servers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "DataCore_Servers"
  },
  {
   "title": "Etat $DataCore_Servers",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"State\") FROM \"DataCore_Servers\" WHERE (\"objectname\" = 'DataCore Servers' AND \"host\" =~ /^$DataCore_Servers$/)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SHOW TAG VALUES WITH KEY = \"OsVersion\" WHERE \"objectname\" = 'DataCore Servers' AND \"host\" =~ /^$DataCore_Servers$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 9, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "DataCore_Servers",
     "select": [
      [
       { "params": [ "CacheState" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$DataCore_Servers$/" }
     ]
    }
   ]
  },
  {
   "title": "Cache Size",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 3 },
   "format": "decgbytes",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "DataCore_Servers",
     "select": [
      [
       { "params": [ "CacheSize" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1024/1024/1024" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$DataCore_Servers$/" }
     ]
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SHOW TAG VALUES WITH KEY = \"ProductName\" WHERE \"objectname\" = 'DataCore Servers' AND \"host\" =~ /^$DataCore_Servers$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 5, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SHOW TAG VALUES WITH KEY = \"ProductVersion\" where \"objectname\" = 'DataCore Servers' AND \"host\" =~ /^$DataCore_Servers$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 9, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "DataCore_Servers",
     "select": [
      [
       { "params": [ "PowerState" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$DataCore_Servers$/" }
     ]
    }
   ]
  },
  {
   "title": "DataCore Server: $DataCore_Servers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 }
  },
  {
   "title": "Etat $DataCore_Servers",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"State\") FROM \"DataCore_Servers\" WHERE (\"objectname\" = 'DataCore Servers' AND \"host\" =~ /^$DataCore_Servers$/)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 10 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SHOW TAG VALUES WITH KEY = \"OsVersion\" WHERE \"objectname\" = 'DataCore Servers' AND \"host\" =~ /^$DataCore_Servers$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 9, "y": 10 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "DataCore_Servers",
     "select": [
      [
       { "params": [ "CacheState" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$DataCore_Servers$/" }
     ]
    }
   ]
  },
  {
   "title": "Cache Size",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 10 },
   "format": "decgbytes",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "DataCore_Servers",
     "select": [
      [
       { "params": [ "CacheSize" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1024/1024/1024" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$DataCore_Servers$/" }
     ]
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 12 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SHOW TAG VALUES WITH KEY = \"ProductName\" where \"objectname\" = 'DataCore Servers' AND \"host\" =~ /^$DataCore_Servers$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 5, "y": 12 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SHOW TAG VALUES WITH KEY = \"ProductVersion\" WHERE \"objectname\" = 'DataCore Servers' AND \"host\" =~ /^$DataCore_Servers$/",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 9, "y": 12 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "DataCore_Servers",
     "select": [
      [
       { "params": [ "PowerState" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$DataCore_Servers$/" }
     ]
    }
   ]
  },
  {
   "title": "DataCore Virtual Disks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Etat: $DataCore_Virtual_Disks",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 15 },
     "repeat": "DataCore_Virtual_Disks",
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "measurement": "DataCore_Virtual_Disks",
       "query": "SELECT last(\"DiskStatus\") FROM \"DataCore_Virtual_Disks\" WHERE (\"instance\" =~ /^$DataCore_Virtual_Disks$/) AND $timeFilter GROUP BY time($__interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Virtual_Disks$/" }
       ]
      }
     ]
    },
    {
     "title": "Size: $DataCore_Virtual_Disks",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 3, "x": 4, "y": 15 },
     "repeat": "DataCore_Virtual_Disks",
     "format": "decgbytes",
     "valueName": "avg",
     "targets": [
      {
       "measurement": "DataCore_Virtual_Disks",
       "query": "SELECT \"value\" FROM \"DataCore_Virtual_Disks\" WHERE (\"instance\" =~ /^$DataCore_Virtual_Disks$/) AND $timeFilter",
       "select": [
        [
         { "params": [ "Size" ], "type": "field" },
         { "params": [ "/1024/1024/1024" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Virtual_Disks$/" }
       ]
      }
     ]
    },
    {
     "title": "$DataCore_Virtual_Disks",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 4, "w": 5, "x": 7, "y": 15 },
     "repeat": "DataCore_Virtual_Disks",
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "alias": "Allocated",
       "measurement": "DataCore_Virtual_Disks",
       "query": "SELECT \"PercentAllocated\" FROM \"DataCore_Virtual_Disks\" WHERE (\"instance\" =~ /^$DataCore_Virtual_Disks$/) AND $timeFilter",
       "select": [
        [
         { "params": [ "PercentAllocated" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Virtual_Disks$/" }
       ]
      },
      {
       "alias": "Available",
       "measurement": "DataCore_Virtual_Disks",
       "query": "SELECT 100 - \"PercentAllocated\"   FROM \"DataCore_Virtual_Disks\" WHERE (\"instance\" =~ /^$DataCore_Virtual_Disks$/) AND $timeFilter",
       "select": [
        [
         { "params": [ "PercentAllocated" ], "type": "field" },
         { "params": [ " / 100" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Virtual_Disks$/" }
       ]
      }
     ]
    },
    {
     "title": "IOPS: $DataCore_Virtual_Disks",
     "type": "graph",
     "gridPos": { "h": 4, "w": 10, "x": 12, "y": 15 },
     "repeat": "DataCore_Virtual_Disks",
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "alias": "Total",
       "measurement": "DataCore_Virtual_Disks",
       "query": "SELECT derivative(\"TotalOperations\", 1s) FROM \"DataCore_Virtual_Disks\" WHERE (\"instance\" =~ /^$DataCore_Virtual_Disks$/) AND $timeFilter",
       "select": [
        [
         { "params": [ "TotalOperations" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Virtual_Disks$/" }
       ]
      },
      {
       "alias": "Reads",
       "measurement": "DataCore_Virtual_Disks",
       "select": [
        [
         { "params": [ "TotalReads" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Virtual_Disks$/" }
       ]
      },
      {
       "alias": "Writes",
       "measurement": "DataCore_Virtual_Disks",
       "select": [
        [
         { "params": [ "TotalWrites" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Virtual_Disks$/" }
       ]
      }
     ]
    },
    {
     "title": "Etat: $DataCore_Virtual_Disks",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 19 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "measurement": "DataCore_Virtual_Disks",
       "query": "SELECT last(\"DiskStatus\") FROM \"DataCore_Virtual_Disks\" WHERE (\"instance\" =~ /^$DataCore_Virtual_Disks$/) AND $timeFilter GROUP BY time($__interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Virtual_Disks$/" }
       ]
      }
     ]
    },
    {
     "title": "Size: $DataCore_Virtual_Disks",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 3, "x": 4, "y": 19 },
     "format": "decgbytes",
     "valueName": "avg",
     "targets": [
      {
       "measurement": "DataCore_Virtual_Disks",
       "query": "SELECT \"value\" FROM \"DataCore_Virtual_Disks\" WHERE (\"instance\" =~ /^$DataCore_Virtual_Disks$/) AND $timeFilter",
       "select": [
        [
         { "params": [ "Size" ], "type": "field" },
         { "params": [ "/1024/1024/1024" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Virtual_Disks$/" }
       ]
      }
     ]
    },
    {
     "title": "$DataCore_Virtual_Disks",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 4, "w": 5, "x": 7, "y": 19 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "alias": "Allocated",
       "measurement": "DataCore_Virtual_Disks",
       "query": "SELECT \"PercentAllocated\" FROM \"DataCore_Virtual_Disks\" WHERE (\"instance\" =~ /^$DataCore_Virtual_Disks$/) AND $timeFilter",
       "select": [
        [
         { "params": [ "PercentAllocated" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Virtual_Disks$/" }
       ]
      },
      {
       "alias": "Available",
       "measurement": "DataCore_Virtual_Disks",
       "query": "SELECT 100 - \"PercentAllocated\"   FROM \"DataCore_Virtual_Disks\" WHERE (\"instance\" =~ /^$DataCore_Virtual_Disks$/) AND $timeFilter",
       "select": [
        [
         { "params": [ "PercentAllocated" ], "type": "field" },
         { "params": [ " / 100" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Virtual_Disks$/" }
       ]
      }
     ]
    },
    {
     "title": "IOPS: $DataCore_Virtual_Disks",
     "type": "graph",
     "gridPos": { "h": 4, "w": 10, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "alias": "Total",
       "measurement": "DataCore_Virtual_Disks",
       "query": "SELECT derivative(\"TotalOperations\", 1s) FROM \"DataCore_Virtual_Disks\" WHERE (\"instance\" =~ /^$DataCore_Virtual_Disks$/) AND $timeFilter",
       "select": [
        [
         { "params": [ "TotalOperations" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Virtual_Disks$/" }
       ]
      },
      {
       "alias": "Reads",
       "measurement": "DataCore_Virtual_Disks",
       "select": [
        [
         { "params": [ "TotalReads" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Virtual_Disks$/" }
       ]
      },
      {
       "alias": "Writes",
       "measurement": "DataCore_Virtual_Disks",
       "select": [
        [
         { "params": [ "TotalWrites" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Virtual_Disks$/" }
       ]
      }
     ]
    },
    {
     "title": "Etat: $DataCore_Virtual_Disks",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 23 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "measurement": "DataCore_Virtual_Disks",
       "query": "SELECT last(\"DiskStatus\") FROM \"DataCore_Virtual_Disks\" WHERE (\"instance\" =~ /^$DataCore_Virtual_Disks$/) AND $timeFilter GROUP BY time($__interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Virtual_Disks$/" }
       ]
      }
     ]
    },
    {
     "title": "Size: $DataCore_Virtual_Disks",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 3, "x": 4, "y": 23 },
     "format": "decgbytes",
     "valueName": "avg",
     "targets": [
      {
       "measurement": "DataCore_Virtual_Disks",
       "query": "SELECT \"value\" FROM \"DataCore_Virtual_Disks\" WHERE (\"instance\" =~ /^$DataCore_Virtual_Disks$/) AND $timeFilter",
       "select": [
        [
         { "params": [ "Size" ], "type": "field" },
         { "params": [ "/1024/1024/1024" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Virtual_Disks$/" }
       ]
      }
     ]
    },
    {
     "title": "$DataCore_Virtual_Disks",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 4, "w": 5, "x": 7, "y": 23 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "alias": "Allocated",
       "measurement": "DataCore_Virtual_Disks",
       "query": "SELECT \"PercentAllocated\" FROM \"DataCore_Virtual_Disks\" WHERE (\"instance\" =~ /^$DataCore_Virtual_Disks$/) AND $timeFilter",
       "select": [
        [
         { "params": [ "PercentAllocated" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Virtual_Disks$/" }
       ]
      },
      {
       "alias": "Available",
       "measurement": "DataCore_Virtual_Disks",
       "query": "SELECT 100 - \"PercentAllocated\"   FROM \"DataCore_Virtual_Disks\" WHERE (\"instance\" =~ /^$DataCore_Virtual_Disks$/) AND $timeFilter",
       "select": [
        [
         { "params": [ "PercentAllocated" ], "type": "field" },
         { "params": [ " / 100" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Virtual_Disks$/" }
       ]
      }
     ]
    },
    {
     "title": "IOPS: $DataCore_Virtual_Disks",
     "type": "graph",
     "gridPos": { "h": 4, "w": 10, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "alias": "Total",
       "measurement": "DataCore_Virtual_Disks",
       "query": "SELECT derivative(\"TotalOperations\", 1s) FROM \"DataCore_Virtual_Disks\" WHERE (\"instance\" =~ /^$DataCore_Virtual_Disks$/) AND $timeFilter",
       "select": [
        [
         { "params": [ "TotalOperations" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Virtual_Disks$/" }
       ]
      },
      {
       "alias": "Reads",
       "measurement": "DataCore_Virtual_Disks",
       "select": [
        [
         { "params": [ "TotalReads" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Virtual_Disks$/" }
       ]
      },
      {
       "alias": "Writes",
       "measurement": "DataCore_Virtual_Disks",
       "select": [
        [
         { "params": [ "TotalWrites" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Virtual_Disks$/" }
       ]
      }
     ]
    },
    {
     "title": "Etat: $DataCore_Virtual_Disks",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 27 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "measurement": "DataCore_Virtual_Disks",
       "query": "SELECT last(\"DiskStatus\") FROM \"DataCore_Virtual_Disks\" WHERE (\"instance\" =~ /^$DataCore_Virtual_Disks$/) AND $timeFilter GROUP BY time($__interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Virtual_Disks$/" }
       ]
      }
     ]
    },
    {
     "title": "Size: $DataCore_Virtual_Disks",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 3, "x": 4, "y": 27 },
     "format": "decgbytes",
     "valueName": "avg",
     "targets": [
      {
       "measurement": "DataCore_Virtual_Disks",
       "query": "SELECT \"value\" FROM \"DataCore_Virtual_Disks\" WHERE (\"instance\" =~ /^$DataCore_Virtual_Disks$/) AND $timeFilter",
       "select": [
        [
         { "params": [ "Size" ], "type": "field" },
         { "params": [ "/1024/1024/1024" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Virtual_Disks$/" }
       ]
      }
     ]
    },
    {
     "title": "$DataCore_Virtual_Disks",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 4, "w": 5, "x": 7, "y": 27 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "alias": "Allocated",
       "measurement": "DataCore_Virtual_Disks",
       "query": "SELECT \"PercentAllocated\" FROM \"DataCore_Virtual_Disks\" WHERE (\"instance\" =~ /^$DataCore_Virtual_Disks$/) AND $timeFilter",
       "select": [
        [
         { "params": [ "PercentAllocated" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Virtual_Disks$/" }
       ]
      },
      {
       "alias": "Available",
       "measurement": "DataCore_Virtual_Disks",
       "query": "SELECT 100 - \"PercentAllocated\"   FROM \"DataCore_Virtual_Disks\" WHERE (\"instance\" =~ /^$DataCore_Virtual_Disks$/) AND $timeFilter",
       "select": [
        [
         { "params": [ "PercentAllocated" ], "type": "field" },
         { "params": [ " / 100" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Virtual_Disks$/" }
       ]
      }
     ]
    },
    {
     "title": "IOPS: $DataCore_Virtual_Disks",
     "type": "graph",
     "gridPos": { "h": 4, "w": 10, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "alias": "Total",
       "measurement": "DataCore_Virtual_Disks",
       "query": "SELECT derivative(\"TotalOperations\", 1s) FROM \"DataCore_Virtual_Disks\" WHERE (\"instance\" =~ /^$DataCore_Virtual_Disks$/) AND $timeFilter",
       "select": [
        [
         { "params": [ "TotalOperations" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Virtual_Disks$/" }
       ]
      },
      {
       "alias": "Reads",
       "measurement": "DataCore_Virtual_Disks",
       "select": [
        [
         { "params": [ "TotalReads" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Virtual_Disks$/" }
       ]
      },
      {
       "alias": "Writes",
       "measurement": "DataCore_Virtual_Disks",
       "select": [
        [
         { "params": [ "TotalWrites" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Virtual_Disks$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "DataCore Pool: $DataCore_Disk_pools",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "repeat": "DataCore_Disk_pools",
   "collapsed": true,
   "panels": [
    {
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 16 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SHOW TAG VALUES WITH KEY = \"Caption\" WHERE \"instance\"  =~ /^$DataCore_Disk_pools$/",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Etat",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 18 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "DataCore_Disk_pools",
       "query": "SELECT last(\"PoolStatus\") FROM \"DataCore_Disk_pools\" WHERE (\"instance\" =~ /^$DataCore_Disk_pools$/)",
       "select": [
        [
         { "params": [ "PoolStatus" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Disk_pools$/" }
       ]
      }
     ]
    },
    {
     "title": "Pool full estimation",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 5, "x": 4, "y": 18 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "DataCore_Disk_pools",
       "select": [
        [
         { "params": [ "EstimatedDepletionTime" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "/60/60/24/1000" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Disk_pools$/" }
       ]
      }
     ]
    },
    {
     "title": "Oversubscription",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 9, "y": 18 },
     "format": "decbytes",
     "valueName": "avg",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "DataCore_Disk_pools",
       "select": [
        [
         { "params": [ "BytesOverSubscribed" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Disk_pools$/" }
       ]
      }
     ]
    },
    { "type": "text", "gridPos": { "h": 5, "w": 12, "x": 12, "y": 18 } },
    {
     "title": "SAU Size",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 0, "y": 20 },
     "format": "decmbytes",
     "valueName": "avg",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "DataCore_Disk_pools",
       "select": [
        [
         { "params": [ "ChunkSize" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "/1024/1024" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Disk_pools$/" }
       ]
      }
     ]
    },
    {
     "title": "Max Tiers",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 3, "y": 20 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "DataCore_Disk_pools",
       "select": [
        [
         { "params": [ "MaxTierNumber" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Disk_pools$/" }
       ]
      }
     ]
    },
    {
     "title": "Tier Preservation",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 5, "y": 20 },
     "format": "percent",
     "valueName": "avg",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "DataCore_Disk_pools",
       "select": [
        [
         { "params": [ "TierReservedPct" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Disk_pools$/" }
       ]
      }
     ]
    },
    {
     "title": "Shared Pool",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 8, "y": 20 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SHOW TAG VALUES WITH KEY = \"InSharedMode\" WHERE \"instance\" =~ /^$DataCore_Disk_pools$/",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 22 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "alias": "Allocated",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "DataCore_Disk_pools",
       "query": "SELECT mean(\"BytesInReclamationPercentage\") FROM \"DataCore_Disk_pools\" WHERE (\"instance\" =~ /^$DataCore_Disk_pools$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "BytesAllocatedPercentage" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Disk_pools$/" }
       ]
      },
      {
       "alias": "Available",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "DataCore_Disk_pools",
       "query": "SELECT mean(\"BytesInReclamationPercentage\") FROM \"DataCore_Disk_pools\" WHERE (\"instance\" =~ /^$DataCore_Disk_pools$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "BytesAvailablePercentage" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Disk_pools$/" }
       ]
      },
      {
       "alias": "Reserved",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "DataCore_Disk_pools",
       "query": "SELECT mean(\"BytesInReclamationPercentage\") FROM \"DataCore_Disk_pools\" WHERE (\"instance\" =~ /^$DataCore_Disk_pools$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "BytesReservedPercentage" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Disk_pools$/" }
       ]
      },
      {
       "alias": "In Reclamation",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "DataCore_Disk_pools",
       "query": "SELECT mean(\"BytesInReclamationPercentage\") FROM \"DataCore_Disk_pools\" WHERE (\"instance\" =~ /^$DataCore_Disk_pools$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "BytesInReclamationPercentage" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Disk_pools$/" }
       ]
      }
     ]
    },
    {
     "title": "Total Capacity",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 10, "y": 23 },
     "format": "decgbytes",
     "valueName": "avg",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "DataCore_Disk_pools",
       "select": [
        [
         { "params": [ "BytesTotal" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "/1024/1024/1024" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Disk_pools$/" }
       ]
      }
     ]
    },
    {
     "title": "Total IOPS",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 15, "y": 23 },
     "format": "iops",
     "valueName": "current",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "DataCore_Disk_pools",
       "select": [
        [
         { "params": [ "TotalOperations" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Disk_pools$/" }
       ]
      }
     ]
    },
    {
     "title": "Reads IOPS",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 18, "y": 23 },
     "format": "iops",
     "valueName": "current",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "DataCore_Disk_pools",
       "select": [
        [
         { "params": [ "TotalReads" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Disk_pools$/" }
       ]
      }
     ]
    },
    {
     "title": "Writes IOPS",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 21, "y": 23 },
     "format": "iops",
     "valueName": "current",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "DataCore_Disk_pools",
       "select": [
        [
         { "params": [ "TotalWrites" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Disk_pools$/" }
       ]
      }
     ]
    },
    {
     "title": "Used Capacity",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 10, "y": 25 },
     "format": "decgbytes",
     "valueName": "avg",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "DataCore_Disk_pools",
       "select": [
        [
         { "params": [ "BytesAllocated" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "/1024/1024/1024" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Disk_pools$/" }
       ]
      }
     ]
    },
    {
     "title": "Latencies",
     "type": "graph",
     "gridPos": { "h": 4, "w": 9, "x": 15, "y": 25 },
     "yaxes": [
      { "format": "ms", "label": "Latencies (ms)" }
     ],
     "targets": [
      {
       "alias": "Read Latency for $tag_instance",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "DataCore_Disk_pools",
       "query": "SELECT derivative(\"TotalReadTime\", 1s)  / derivative(\"TotalReads\", 1s)  FROM \"DataCore_Disk_pools\" WHERE (\"instance\" = 'SDS2-Pool1 on SDS2') AND $timeFilter GROUP BY \"instance\"",
       "select": [
        [
         { "params": [ "TotalReadTime" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" },
         {
          "params": [
           " / derivative(\"TotalReads\", 1s) "
          ],
          "type": "math"
         }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Disk_pools$/" }
       ]
      },
      {
       "alias": "Write Latency for $tag_instance",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "DataCore_Disk_pools",
       "query": "SELECT derivative(\"TotalWriteTime\", 1s) FROM \"DataCore_Disk_pools\" WHERE (\"instance\" =~ /^$DataCore_Disk_pools$/) AND $timeFilter GROUP BY \"instance\"",
       "select": [
        [
         { "params": [ "TotalWriteTime" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" },
         {
          "params": [
           " / derivative(\"TotalWrites\", 1s)"
          ],
          "type": "math"
         }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Disk_pools$/" }
       ]
      }
     ]
    },
    {
     "title": "Free Capacity",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 10, "y": 27 },
     "format": "decgbytes",
     "valueName": "avg",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "DataCore_Disk_pools",
       "select": [
        [
         { "params": [ "BytesAvailable" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "/1024/1024/1024" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Disk_pools$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "DataCore Pool: $DataCore_Disk_pools",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 16 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SHOW TAG VALUES WITH KEY = \"Caption\" WHERE \"instance\"  =~ /^$DataCore_Disk_pools$/",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Etat",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 4, "x": 0, "y": 18 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "DataCore_Disk_pools",
       "query": "SELECT last(\"PoolStatus\") FROM \"DataCore_Disk_pools\" WHERE (\"instance\" =~ /^$DataCore_Disk_pools$/)",
       "select": [
        [
         { "params": [ "PoolStatus" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Disk_pools$/" }
       ]
      }
     ]
    },
    {
     "title": "Pool full estimation",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 5, "x": 4, "y": 18 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "DataCore_Disk_pools",
       "select": [
        [
         { "params": [ "EstimatedDepletionTime" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "/60/60/24/1000" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Disk_pools$/" }
       ]
      }
     ]
    },
    {
     "title": "Oversubscription",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 9, "y": 18 },
     "format": "decbytes",
     "valueName": "avg",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "DataCore_Disk_pools",
       "select": [
        [
         { "params": [ "BytesOverSubscribed" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Disk_pools$/" }
       ]
      }
     ]
    },
    { "type": "text", "gridPos": { "h": 5, "w": 12, "x": 12, "y": 18 } },
    {
     "title": "SAU Size",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 0, "y": 20 },
     "format": "decmbytes",
     "valueName": "avg",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "DataCore_Disk_pools",
       "select": [
        [
         { "params": [ "ChunkSize" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "/1024/1024" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Disk_pools$/" }
       ]
      }
     ]
    },
    {
     "title": "Max Tiers",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 3, "y": 20 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "DataCore_Disk_pools",
       "select": [
        [
         { "params": [ "MaxTierNumber" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Disk_pools$/" }
       ]
      }
     ]
    },
    {
     "title": "Tier Preservation",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 5, "y": 20 },
     "format": "percent",
     "valueName": "avg",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "DataCore_Disk_pools",
       "select": [
        [
         { "params": [ "TierReservedPct" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Disk_pools$/" }
       ]
      }
     ]
    },
    {
     "title": "Shared Pool",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 2, "x": 8, "y": 20 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SHOW TAG VALUES WITH KEY = \"InSharedMode\" WHERE \"instance\" =~ /^$DataCore_Disk_pools$/",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 22 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "alias": "Allocated",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "DataCore_Disk_pools",
       "query": "SELECT mean(\"BytesInReclamationPercentage\") FROM \"DataCore_Disk_pools\" WHERE (\"instance\" =~ /^$DataCore_Disk_pools$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "BytesAllocatedPercentage" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Disk_pools$/" }
       ]
      },
      {
       "alias": "Available",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "DataCore_Disk_pools",
       "query": "SELECT mean(\"BytesInReclamationPercentage\") FROM \"DataCore_Disk_pools\" WHERE (\"instance\" =~ /^$DataCore_Disk_pools$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "BytesAvailablePercentage" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Disk_pools$/" }
       ]
      },
      {
       "alias": "Reserved",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "DataCore_Disk_pools",
       "query": "SELECT mean(\"BytesInReclamationPercentage\") FROM \"DataCore_Disk_pools\" WHERE (\"instance\" =~ /^$DataCore_Disk_pools$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "BytesReservedPercentage" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Disk_pools$/" }
       ]
      },
      {
       "alias": "In Reclamation",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "DataCore_Disk_pools",
       "query": "SELECT mean(\"BytesInReclamationPercentage\") FROM \"DataCore_Disk_pools\" WHERE (\"instance\" =~ /^$DataCore_Disk_pools$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "BytesInReclamationPercentage" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Disk_pools$/" }
       ]
      }
     ]
    },
    {
     "title": "Total Capacity",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 10, "y": 23 },
     "format": "decgbytes",
     "valueName": "avg",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "DataCore_Disk_pools",
       "select": [
        [
         { "params": [ "BytesTotal" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "/1024/1024/1024" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Disk_pools$/" }
       ]
      }
     ]
    },
    {
     "title": "Total IOPS",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 15, "y": 23 },
     "format": "iops",
     "valueName": "current",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "DataCore_Disk_pools",
       "select": [
        [
         { "params": [ "TotalOperations" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Disk_pools$/" }
       ]
      }
     ]
    },
    {
     "title": "Reads IOPS",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 18, "y": 23 },
     "format": "iops",
     "valueName": "current",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "DataCore_Disk_pools",
       "select": [
        [
         { "params": [ "TotalReads" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Disk_pools$/" }
       ]
      }
     ]
    },
    {
     "title": "Writes IOPS",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 21, "y": 23 },
     "format": "iops",
     "valueName": "current",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "DataCore_Disk_pools",
       "select": [
        [
         { "params": [ "TotalWrites" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Disk_pools$/" }
       ]
      }
     ]
    },
    {
     "title": "Used Capacity",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 10, "y": 25 },
     "format": "decgbytes",
     "valueName": "avg",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "DataCore_Disk_pools",
       "select": [
        [
         { "params": [ "BytesAllocated" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "/1024/1024/1024" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Disk_pools$/" }
       ]
      }
     ]
    },
    {
     "title": "Latencies",
     "type": "graph",
     "gridPos": { "h": 4, "w": 9, "x": 15, "y": 25 },
     "yaxes": [
      { "format": "ms", "label": "Latencies (ms)" }
     ],
     "targets": [
      {
       "alias": "Read Latency for $tag_instance",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "DataCore_Disk_pools",
       "query": "SELECT derivative(\"TotalReadTime\", 1s)  / derivative(\"TotalReads\", 1s)  FROM \"DataCore_Disk_pools\" WHERE (\"instance\" = 'SDS2-Pool1 on SDS2') AND $timeFilter GROUP BY \"instance\"",
       "select": [
        [
         { "params": [ "TotalReadTime" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" },
         {
          "params": [
           " / derivative(\"TotalReads\", 1s) "
          ],
          "type": "math"
         }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Disk_pools$/" }
       ]
      },
      {
       "alias": "Write Latency for $tag_instance",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "DataCore_Disk_pools",
       "query": "SELECT derivative(\"TotalWriteTime\", 1s) FROM \"DataCore_Disk_pools\" WHERE (\"instance\" =~ /^$DataCore_Disk_pools$/) AND $timeFilter GROUP BY \"instance\"",
       "select": [
        [
         { "params": [ "TotalWriteTime" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" },
         {
          "params": [
           " / derivative(\"TotalWrites\", 1s)"
          ],
          "type": "math"
         }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Disk_pools$/" }
       ]
      }
     ]
    },
    {
     "title": "Free Capacity",
     "type": "singlestat",
     "gridPos": { "h": 2, "w": 3, "x": 10, "y": 27 },
     "format": "decgbytes",
     "valueName": "avg",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "DataCore_Disk_pools",
       "select": [
        [
         { "params": [ "BytesAvailable" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         },
         { "params": [ "/1024/1024/1024" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Disk_pools$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "DataCore Physical Disks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Etat: $DataCore_Physical_Disks",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 18 },
     "repeat": "DataCore_Physical_Disks",
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "measurement": "DataCore_Physical_disk",
       "query": "SELECT last(\"DiskStatus\") FROM \"DataCore_Pysical_Disks\" WHERE (\"instance\" =~ /^$DataCore_Pysical_Disks$/) AND $timeFilter GROUP BY time($__interval)",
       "select": [
        [
         { "params": [ "DiskStatus" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Physical_Disks$/" },
        { "condition": "AND", "key": "Type", "operator": "=", "value": "4" }
       ]
      }
     ]
    },
    {
     "title": "IOPS: $DataCore_Physical_Disks",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 4, "y": 18 },
     "repeat": "DataCore_Physical_Disks",
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "alias": "Total",
       "measurement": "DataCore_Physical_disk",
       "query": "SELECT derivative(\"TotalOperations\", 1s) FROM \"DataCore_Virtual_Disks\" WHERE (\"instance\" =~ /^$DataCore_Virtual_Disks$/) AND $timeFilter",
       "select": [
        [
         { "params": [ "TotalOperations" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Physical_Disks$/" }
       ]
      },
      {
       "alias": "Reads",
       "measurement": "DataCore_Physical_disk",
       "select": [
        [
         { "params": [ "TotalReads" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Physical_Disks$/" }
       ]
      },
      {
       "alias": "Writes",
       "measurement": "DataCore_Physical_disk",
       "select": [
        [
         { "params": [ "TotalWrites" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Physical_Disks$/" }
       ]
      }
     ]
    },
    {
     "title": "Latencies",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 18 },
     "repeat": "DataCore_Physical_Disks",
     "yaxes": [
      { "format": "ms", "label": "Latencies (ms)" }
     ],
     "targets": [
      {
       "alias": "Read Latency for $tag_instance",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "DataCore_Physical_disk",
       "query": "SELECT derivative(\"TotalReadTime\", 1s)  / derivative(\"TotalReads\", 1s)  FROM \"DataCore_Disk_pools\" WHERE (\"instance\" = 'SDS2-Pool1 on SDS2') AND $timeFilter GROUP BY \"instance\"",
       "select": [
        [
         { "params": [ "TotalReadsTime" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" },
         {
          "params": [
           " / derivative(\"TotalReads\", 1s) "
          ],
          "type": "math"
         }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Physical_Disks$/" }
       ]
      },
      {
       "alias": "Write Latency for $tag_instance",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "DataCore_Physical_disk",
       "query": "SELECT derivative(\"TotalWriteTime\", 1s) FROM \"DataCore_Disk_pools\" WHERE (\"instance\" =~ /^$DataCore_Disk_pools$/) AND $timeFilter GROUP BY \"instance\"",
       "select": [
        [
         { "params": [ "TotalWritesTime" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" },
         {
          "params": [
           " / derivative(\"TotalWrites\", 1s)"
          ],
          "type": "math"
         }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Physical_Disks$/" }
       ]
      }
     ]
    },
    {
     "title": "Etat: $DataCore_Physical_Disks",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 24 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "measurement": "DataCore_Physical_disk",
       "query": "SELECT last(\"DiskStatus\") FROM \"DataCore_Pysical_Disks\" WHERE (\"instance\" =~ /^$DataCore_Pysical_Disks$/) AND $timeFilter GROUP BY time($__interval)",
       "select": [
        [
         { "params": [ "DiskStatus" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Physical_Disks$/" },
        { "condition": "AND", "key": "Type", "operator": "=", "value": "4" }
       ]
      }
     ]
    },
    {
     "title": "IOPS: $DataCore_Physical_Disks",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 4, "y": 24 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "alias": "Total",
       "measurement": "DataCore_Physical_disk",
       "query": "SELECT derivative(\"TotalOperations\", 1s) FROM \"DataCore_Virtual_Disks\" WHERE (\"instance\" =~ /^$DataCore_Virtual_Disks$/) AND $timeFilter",
       "select": [
        [
         { "params": [ "TotalOperations" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Physical_Disks$/" }
       ]
      },
      {
       "alias": "Reads",
       "measurement": "DataCore_Physical_disk",
       "select": [
        [
         { "params": [ "TotalReads" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Physical_Disks$/" }
       ]
      },
      {
       "alias": "Writes",
       "measurement": "DataCore_Physical_disk",
       "select": [
        [
         { "params": [ "TotalWrites" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Physical_Disks$/" }
       ]
      }
     ]
    },
    {
     "title": "Latencies",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 24 },
     "yaxes": [
      { "format": "ms", "label": "Latencies (ms)" }
     ],
     "targets": [
      {
       "alias": "Read Latency for $tag_instance",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "DataCore_Physical_disk",
       "query": "SELECT derivative(\"TotalReadTime\", 1s)  / derivative(\"TotalReads\", 1s)  FROM \"DataCore_Disk_pools\" WHERE (\"instance\" = 'SDS2-Pool1 on SDS2') AND $timeFilter GROUP BY \"instance\"",
       "select": [
        [
         { "params": [ "TotalReadsTime" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" },
         {
          "params": [
           " / derivative(\"TotalReads\", 1s) "
          ],
          "type": "math"
         }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Physical_Disks$/" }
       ]
      },
      {
       "alias": "Write Latency for $tag_instance",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "DataCore_Physical_disk",
       "query": "SELECT derivative(\"TotalWriteTime\", 1s) FROM \"DataCore_Disk_pools\" WHERE (\"instance\" =~ /^$DataCore_Disk_pools$/) AND $timeFilter GROUP BY \"instance\"",
       "select": [
        [
         { "params": [ "TotalWritesTime" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" },
         {
          "params": [
           " / derivative(\"TotalWrites\", 1s)"
          ],
          "type": "math"
         }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Physical_Disks$/" }
       ]
      }
     ]
    },
    {
     "title": "Etat: $DataCore_Physical_Disks",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 30 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "measurement": "DataCore_Physical_disk",
       "query": "SELECT last(\"DiskStatus\") FROM \"DataCore_Pysical_Disks\" WHERE (\"instance\" =~ /^$DataCore_Pysical_Disks$/) AND $timeFilter GROUP BY time($__interval)",
       "select": [
        [
         { "params": [ "DiskStatus" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Physical_Disks$/" },
        { "condition": "AND", "key": "Type", "operator": "=", "value": "4" }
       ]
      }
     ]
    },
    {
     "title": "IOPS: $DataCore_Physical_Disks",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 4, "y": 30 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "alias": "Total",
       "measurement": "DataCore_Physical_disk",
       "query": "SELECT derivative(\"TotalOperations\", 1s) FROM \"DataCore_Virtual_Disks\" WHERE (\"instance\" =~ /^$DataCore_Virtual_Disks$/) AND $timeFilter",
       "select": [
        [
         { "params": [ "TotalOperations" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Physical_Disks$/" }
       ]
      },
      {
       "alias": "Reads",
       "measurement": "DataCore_Physical_disk",
       "select": [
        [
         { "params": [ "TotalReads" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Physical_Disks$/" }
       ]
      },
      {
       "alias": "Writes",
       "measurement": "DataCore_Physical_disk",
       "select": [
        [
         { "params": [ "TotalWrites" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Physical_Disks$/" }
       ]
      }
     ]
    },
    {
     "title": "Latencies",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 30 },
     "yaxes": [
      { "format": "ms", "label": "Latencies (ms)" }
     ],
     "targets": [
      {
       "alias": "Read Latency for $tag_instance",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "DataCore_Physical_disk",
       "query": "SELECT derivative(\"TotalReadTime\", 1s)  / derivative(\"TotalReads\", 1s)  FROM \"DataCore_Disk_pools\" WHERE (\"instance\" = 'SDS2-Pool1 on SDS2') AND $timeFilter GROUP BY \"instance\"",
       "select": [
        [
         { "params": [ "TotalReadsTime" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" },
         {
          "params": [
           " / derivative(\"TotalReads\", 1s) "
          ],
          "type": "math"
         }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Physical_Disks$/" }
       ]
      },
      {
       "alias": "Write Latency for $tag_instance",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "DataCore_Physical_disk",
       "query": "SELECT derivative(\"TotalWriteTime\", 1s) FROM \"DataCore_Disk_pools\" WHERE (\"instance\" =~ /^$DataCore_Disk_pools$/) AND $timeFilter GROUP BY \"instance\"",
       "select": [
        [
         { "params": [ "TotalWritesTime" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" },
         {
          "params": [
           " / derivative(\"TotalWrites\", 1s)"
          ],
          "type": "math"
         }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Physical_Disks$/" }
       ]
      }
     ]
    },
    {
     "title": "Etat: $DataCore_Physical_Disks",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 36 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "measurement": "DataCore_Physical_disk",
       "query": "SELECT last(\"DiskStatus\") FROM \"DataCore_Pysical_Disks\" WHERE (\"instance\" =~ /^$DataCore_Pysical_Disks$/) AND $timeFilter GROUP BY time($__interval)",
       "select": [
        [
         { "params": [ "DiskStatus" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Physical_Disks$/" },
        { "condition": "AND", "key": "Type", "operator": "=", "value": "4" }
       ]
      }
     ]
    },
    {
     "title": "IOPS: $DataCore_Physical_Disks",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 4, "y": 36 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "alias": "Total",
       "measurement": "DataCore_Physical_disk",
       "query": "SELECT derivative(\"TotalOperations\", 1s) FROM \"DataCore_Virtual_Disks\" WHERE (\"instance\" =~ /^$DataCore_Virtual_Disks$/) AND $timeFilter",
       "select": [
        [
         { "params": [ "TotalOperations" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Physical_Disks$/" }
       ]
      },
      {
       "alias": "Reads",
       "measurement": "DataCore_Physical_disk",
       "select": [
        [
         { "params": [ "TotalReads" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Physical_Disks$/" }
       ]
      },
      {
       "alias": "Writes",
       "measurement": "DataCore_Physical_disk",
       "select": [
        [
         { "params": [ "TotalWrites" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Physical_Disks$/" }
       ]
      }
     ]
    },
    {
     "title": "Latencies",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 36 },
     "yaxes": [
      { "format": "ms", "label": "Latencies (ms)" }
     ],
     "targets": [
      {
       "alias": "Read Latency for $tag_instance",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "DataCore_Physical_disk",
       "query": "SELECT derivative(\"TotalReadTime\", 1s)  / derivative(\"TotalReads\", 1s)  FROM \"DataCore_Disk_pools\" WHERE (\"instance\" = 'SDS2-Pool1 on SDS2') AND $timeFilter GROUP BY \"instance\"",
       "select": [
        [
         { "params": [ "TotalReadsTime" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" },
         {
          "params": [
           " / derivative(\"TotalReads\", 1s) "
          ],
          "type": "math"
         }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Physical_Disks$/" }
       ]
      },
      {
       "alias": "Write Latency for $tag_instance",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "DataCore_Physical_disk",
       "query": "SELECT derivative(\"TotalWriteTime\", 1s) FROM \"DataCore_Disk_pools\" WHERE (\"instance\" =~ /^$DataCore_Disk_pools$/) AND $timeFilter GROUP BY \"instance\"",
       "select": [
        [
         { "params": [ "TotalWritesTime" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" },
         {
          "params": [
           " / derivative(\"TotalWrites\", 1s)"
          ],
          "type": "math"
         }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Physical_Disks$/" }
       ]
      }
     ]
    }
   ]
  }
 ]
}