{
 "title": "DataCore Monitor V1.3",
 "tags": [
  "DataCore_REST",
  "All Dashboards"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "DataCore_Servers",
    "label": "DataCore Servers",
    "query": "SHOW TAG VALUES WITH KEY = \"host\" WHERE \"objectname\" = 'DataCore Servers'"
   },
   {
    "name": "DataCore_Virtual_Disks",
    "label": "DataCore Virtual Disks",
    "query": "SHOW TAG VALUES WITH KEY = \"instance\" WHERE \"objectname\" = 'DataCore Virtual disks' and \"instance\" !~ /^Logstore/"
   },
   {
    "name": "DataCore_Disk_pools",
    "label": "DataCore Disk Pools",
    "query": "SHOW TAG VALUES WITH KEY = \"instance\" WHERE \"objectname\" = 'DataCore Disk pools'"
   },
   {
    "name": "DataCore_Physical_Disks",
    "label": "DataCore Physical Disk",
    "query": "SHOW TAG VALUES WITH KEY = \"instance\" WHERE \"objectname\" = 'DataCore Physical disk' and \"Type\" = '4'"
   },
   {
    "name": "DataCore_SCSI_Ports",
    "label": "DataCore SCSI Ports",
    "query": "SHOW TAG VALUES WITH KEY = \"instance\" WHERE \"objectname\" = 'DataCore SCSI ports' and (\"PortRole\" = '1' or \"PortRole\" = '2' or \"PortRole\" = '4' )"
   }
  ]
 },
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "DataCore Servers",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DataCore_State",
     "query": "SELECT last(\"State\"), \"Caption\" FROM \"DataCore_Servers\" WHERE (\"objectname\" = 'DataCore Servers' AND \"host\" =~ /^$DataCore_Servers$/) group by \"host\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "objectname", "operator": "=", "value": "DataCore Servers" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$DataCore_Servers$/" }
     ]
    }
   ]
  },
  {
   "title": "DataCore vDisks",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "DataCore_State",
     "query": "SELECT last(\"DiskStatus\") FROM \"DataCore_Virtual_Disks\" WHERE (\"objectname\" = 'DataCore Virtual disks' and \"instance\" =~ /^$DataCore_Virtual_Disks$/)  group by instance",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "objectname", "operator": "=", "value": "DataCore Virtual disks" }
     ]
    }
   ]
  },
  {
   "title": "DataCore Servers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "$DataCore_Servers - Total OPS",
     "type": "graph",
     "gridPos": { "h": 9, "w": 9, "x": 0, "y": 2 },
     "repeat": "DataCore_Servers",
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "alias": "$tag_instance : Reads",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "DataCore_Servers",
       "select": [
        [
         { "params": [ "TotalReads" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$DataCore_Servers$/" }
       ]
      },
      {
       "alias": "$tag_instance : Writes",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "DataCore_Servers",
       "select": [
        [
         { "params": [ "TotalWrites" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$DataCore_Servers$/" }
       ]
      },
      {
       "alias": "$tag_instance : Total",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "DataCore_Servers",
       "select": [
        [
         { "params": [ "TotalOperations" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$DataCore_Servers$/" }
       ]
      }
     ]
    },
    {
     "title": "$DataCore_Servers - Front End OPS",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 9, "y": 2 },
     "repeat": "DataCore_Servers",
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "alias": "$tag_instance : Front End OPS",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "DataCore_Servers",
       "select": [
        [
         { "params": [ "FrontEndTargetOperations" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$DataCore_Servers$/" }
       ]
      }
     ]
    },
    {
     "title": "$DataCore_Servers - Front End Bandwidth",
     "type": "graph",
     "gridPos": { "h": 9, "w": 7, "x": 17, "y": 2 },
     "repeat": "DataCore_Servers",
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "$tag_instance : Front End OPS",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "DataCore_Servers",
       "select": [
        [
         { "params": [ "FrontEndTargetBytesTransfered" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$DataCore_Servers$/" }
       ]
      }
     ]
    },
    {
     "title": "$DataCore_Servers - Total OPS",
     "type": "graph",
     "gridPos": { "h": 9, "w": 9, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "alias": "$tag_instance : Reads",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "DataCore_Servers",
       "select": [
        [
         { "params": [ "TotalReads" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$DataCore_Servers$/" }
       ]
      },
      {
       "alias": "$tag_instance : Writes",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "DataCore_Servers",
       "select": [
        [
         { "params": [ "TotalWrites" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$DataCore_Servers$/" }
       ]
      },
      {
       "alias": "$tag_instance : Total",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "DataCore_Servers",
       "select": [
        [
         { "params": [ "TotalOperations" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$DataCore_Servers$/" }
       ]
      }
     ]
    },
    {
     "title": "$DataCore_Servers - Front End OPS",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 9, "y": 11 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "alias": "$tag_instance : Front End OPS",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "DataCore_Servers",
       "select": [
        [
         { "params": [ "FrontEndTargetOperations" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$DataCore_Servers$/" }
       ]
      }
     ]
    },
    {
     "title": "$DataCore_Servers - Front End Bandwidth",
     "type": "graph",
     "gridPos": { "h": 9, "w": 7, "x": 17, "y": 11 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "alias": "$tag_instance : Front End OPS",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "DataCore_Servers",
       "select": [
        [
         { "params": [ "FrontEndTargetBytesTransfered" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$DataCore_Servers$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "DataCore Virtual Disks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "$DataCore_Virtual_Disks: IOPS",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 3 },
     "repeat": "DataCore_Virtual_Disks",
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "alias": "$tag_instance : Reads",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "DataCore_Virtual_Disks",
       "query": "SELECT derivative(\"TotalReads\", 1s) FROM \"DataCore_Virtual_Disks\" WHERE (\"instance\" =~ /^$DataCore_Virtual_Disks$/) AND $timeFilter GROUP BY \"instance\"",
       "select": [
        [
         { "params": [ "TotalReads" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Virtual_Disks$/" }
       ]
      },
      {
       "alias": "$tag_instance : Writes",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "DataCore_Virtual_Disks",
       "select": [
        [
         { "params": [ "TotalWrites" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Virtual_Disks$/" }
       ]
      },
      {
       "alias": "$tag_instance : Total",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "DataCore_Virtual_Disks",
       "select": [
        [
         { "params": [ "TotalOperations" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Virtual_Disks$/" }
       ]
      },
      {
       "alias": "$tag_instance : Cache Read Misses",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "DataCore_Virtual_Disks",
       "select": [
        [
         { "params": [ "CacheReadMisses" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Virtual_Disks$/" }
       ]
      },
      {
       "alias": "$tag_instance : Cache Write Misses",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "DataCore_Virtual_Disks",
       "select": [
        [
         { "params": [ "CacheWriteMisses" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Virtual_Disks$/" }
       ]
      }
     ]
    },
    {
     "title": "$DataCore_Virtual_Disks: IOPS",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "alias": "$tag_instance : Reads",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "DataCore_Virtual_Disks",
       "query": "SELECT derivative(\"TotalReads\", 1s) FROM \"DataCore_Virtual_Disks\" WHERE (\"instance\" =~ /^$DataCore_Virtual_Disks$/) AND $timeFilter GROUP BY \"instance\"",
       "select": [
        [
         { "params": [ "TotalReads" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Virtual_Disks$/" }
       ]
      },
      {
       "alias": "$tag_instance : Writes",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "DataCore_Virtual_Disks",
       "select": [
        [
         { "params": [ "TotalWrites" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Virtual_Disks$/" }
       ]
      },
      {
       "alias": "$tag_instance : Total",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "DataCore_Virtual_Disks",
       "select": [
        [
         { "params": [ "TotalOperations" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Virtual_Disks$/" }
       ]
      },
      {
       "alias": "$tag_instance : Cache Read Misses",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "DataCore_Virtual_Disks",
       "select": [
        [
         { "params": [ "CacheReadMisses" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Virtual_Disks$/" }
       ]
      },
      {
       "alias": "$tag_instance : Cache Write Misses",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "DataCore_Virtual_Disks",
       "select": [
        [
         { "params": [ "CacheWriteMisses" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Virtual_Disks$/" }
       ]
      }
     ]
    },
    {
     "title": "$DataCore_Virtual_Disks: IOPS",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "alias": "$tag_instance : Reads",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "DataCore_Virtual_Disks",
       "query": "SELECT derivative(\"TotalReads\", 1s) FROM \"DataCore_Virtual_Disks\" WHERE (\"instance\" =~ /^$DataCore_Virtual_Disks$/) AND $timeFilter GROUP BY \"instance\"",
       "select": [
        [
         { "params": [ "TotalReads" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Virtual_Disks$/" }
       ]
      },
      {
       "alias": "$tag_instance : Writes",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "DataCore_Virtual_Disks",
       "select": [
        [
         { "params": [ "TotalWrites" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Virtual_Disks$/" }
       ]
      },
      {
       "alias": "$tag_instance : Total",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "DataCore_Virtual_Disks",
       "select": [
        [
         { "params": [ "TotalOperations" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Virtual_Disks$/" }
       ]
      },
      {
       "alias": "$tag_instance : Cache Read Misses",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "DataCore_Virtual_Disks",
       "select": [
        [
         { "params": [ "CacheReadMisses" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Virtual_Disks$/" }
       ]
      },
      {
       "alias": "$tag_instance : Cache Write Misses",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "DataCore_Virtual_Disks",
       "select": [
        [
         { "params": [ "CacheWriteMisses" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Virtual_Disks$/" }
       ]
      }
     ]
    },
    {
     "title": "$DataCore_Virtual_Disks: IOPS",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "alias": "$tag_instance : Reads",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "DataCore_Virtual_Disks",
       "query": "SELECT derivative(\"TotalReads\", 1s) FROM \"DataCore_Virtual_Disks\" WHERE (\"instance\" =~ /^$DataCore_Virtual_Disks$/) AND $timeFilter GROUP BY \"instance\"",
       "select": [
        [
         { "params": [ "TotalReads" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Virtual_Disks$/" }
       ]
      },
      {
       "alias": "$tag_instance : Writes",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "DataCore_Virtual_Disks",
       "select": [
        [
         { "params": [ "TotalWrites" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Virtual_Disks$/" }
       ]
      },
      {
       "alias": "$tag_instance : Total",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "DataCore_Virtual_Disks",
       "select": [
        [
         { "params": [ "TotalOperations" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Virtual_Disks$/" }
       ]
      },
      {
       "alias": "$tag_instance : Cache Read Misses",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "DataCore_Virtual_Disks",
       "select": [
        [
         { "params": [ "CacheReadMisses" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Virtual_Disks$/" }
       ]
      },
      {
       "alias": "$tag_instance : Cache Write Misses",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "DataCore_Virtual_Disks",
       "select": [
        [
         { "params": [ "CacheWriteMisses" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Virtual_Disks$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "DataCore Pools",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "$DataCore_Disk_pools - IOPS",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
     "repeat": "DataCore_Disk_pools",
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "alias": "$tag_instance : Reads",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "DataCore_Disk_pools",
       "select": [
        [
         { "params": [ "TotalReads" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Disk_pools$/" }
       ]
      },
      {
       "alias": "$tag_instance : Writes",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "DataCore_Disk_pools",
       "select": [
        [
         { "params": [ "TotalWrites" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Disk_pools$/" }
       ]
      },
      {
       "alias": "$tag_instance : Total",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "DataCore_Disk_pools",
       "select": [
        [
         { "params": [ "TotalOperations" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Disk_pools$/" }
       ]
      }
     ]
    },
    {
     "title": "$DataCore_Disk_pools - Latency",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
     "repeat": "DataCore_Disk_pools",
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "Read",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "DataCore_Disk_pools",
       "query": "SELECT derivative(\"TotalReadTime\", 1s)  / derivative(\"TotalReads\", 1s) FROM \"DataCore_Disk_pools\" WHERE (\"instance\" =~ /^$DataCore_Disk_pools$/) AND $timeFilter GROUP BY \"instance\"",
       "select": [
        [
         { "params": [ "TotalReadTime" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" },
         {
          "params": [
           " / derivative(\"TotalReads\", 1s)"
          ],
          "type": "math"
         }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Disk_pools$/" }
       ]
      },
      {
       "alias": "Write",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "DataCore_Disk_pools",
       "query": "SELECT derivative(\"TotalWrites\", 1s) FROM \"DataCore_Disk_pools\" WHERE (\"instance\" =~ /^$DataCore_Disk_pools$/) AND $timeFilter GROUP BY \"instance\"",
       "select": [
        [
         { "params": [ "TotalWriteTime" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" },
         {
          "params": [
           " / derivative(\"TotalWrites\", 1s)"
          ],
          "type": "math"
         }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Disk_pools$/" }
       ]
      }
     ]
    },
    {
     "title": "$DataCore_Disk_pools - IOPS",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "alias": "$tag_instance : Reads",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "DataCore_Disk_pools",
       "select": [
        [
         { "params": [ "TotalReads" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Disk_pools$/" }
       ]
      },
      {
       "alias": "$tag_instance : Writes",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "DataCore_Disk_pools",
       "select": [
        [
         { "params": [ "TotalWrites" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Disk_pools$/" }
       ]
      },
      {
       "alias": "$tag_instance : Total",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "DataCore_Disk_pools",
       "select": [
        [
         { "params": [ "TotalOperations" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Disk_pools$/" }
       ]
      }
     ]
    },
    {
     "title": "$DataCore_Disk_pools - Latency",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "Read",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "DataCore_Disk_pools",
       "query": "SELECT derivative(\"TotalReadTime\", 1s)  / derivative(\"TotalReads\", 1s) FROM \"DataCore_Disk_pools\" WHERE (\"instance\" =~ /^$DataCore_Disk_pools$/) AND $timeFilter GROUP BY \"instance\"",
       "select": [
        [
         { "params": [ "TotalReadTime" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" },
         {
          "params": [
           " / derivative(\"TotalReads\", 1s)"
          ],
          "type": "math"
         }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Disk_pools$/" }
       ]
      },
      {
       "alias": "Write",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "DataCore_Disk_pools",
       "query": "SELECT derivative(\"TotalWrites\", 1s) FROM \"DataCore_Disk_pools\" WHERE (\"instance\" =~ /^$DataCore_Disk_pools$/) AND $timeFilter GROUP BY \"instance\"",
       "select": [
        [
         { "params": [ "TotalWriteTime" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" },
         {
          "params": [
           " / derivative(\"TotalWrites\", 1s)"
          ],
          "type": "math"
         }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Disk_pools$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "DataCore Physical Disks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "$DataCore_Physical_Disks - IOPS",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
     "repeat": "DataCore_Physical_Disks",
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "alias": "$tag_instance : Reads",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "DataCore_Physical_disk",
       "select": [
        [
         { "params": [ "TotalReads" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Physical_Disks$/" }
       ]
      },
      {
       "alias": "$tag_instance : Writes",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "DataCore_Physical_disk",
       "select": [
        [
         { "params": [ "TotalWrites" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Physical_Disks$/" }
       ]
      },
      {
       "alias": "$tag_instance : Total",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "DataCore_Physical_disk",
       "select": [
        [
         { "params": [ "TotalOperations" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Physical_Disks$/" }
       ]
      }
     ]
    },
    {
     "title": "$DataCore_Physical_Disks - Latency",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
     "repeat": "DataCore_Physical_Disks",
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$tag_instance : Reads",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "DataCore_Physical_disk",
       "query": "SELECT derivative(\"TotalReads\", 1s) FROM \"DataCore_Physical_disk\" WHERE (\"instance\" =~ /^$DataCore_Physical_Disks$/) AND $timeFilter GROUP BY \"instance\"",
       "select": [
        [
         { "params": [ "TotalReadsTime" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" },
         {
          "params": [
           " /  derivative(\"TotalReads\", 1s)"
          ],
          "type": "math"
         }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Physical_Disks$/" }
       ]
      },
      {
       "alias": "$tag_instance : Writes",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "DataCore_Physical_disk",
       "query": "SELECT derivative(\"TotalWrites\", 1s) FROM \"DataCore_Physical_disk\" WHERE (\"instance\" =~ /^$DataCore_Physical_Disks$/) AND $timeFilter GROUP BY \"instance\"",
       "select": [
        [
         { "params": [ "TotalWritesTime" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" },
         {
          "params": [
           " / derivative(\"TotalWrites\", 1s)"
          ],
          "type": "math"
         }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Physical_Disks$/" }
       ]
      }
     ]
    },
    {
     "title": "$DataCore_Physical_Disks - IOPS",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "alias": "$tag_instance : Reads",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "DataCore_Physical_disk",
       "select": [
        [
         { "params": [ "TotalReads" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Physical_Disks$/" }
       ]
      },
      {
       "alias": "$tag_instance : Writes",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "DataCore_Physical_disk",
       "select": [
        [
         { "params": [ "TotalWrites" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Physical_Disks$/" }
       ]
      },
      {
       "alias": "$tag_instance : Total",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "DataCore_Physical_disk",
       "select": [
        [
         { "params": [ "TotalOperations" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Physical_Disks$/" }
       ]
      }
     ]
    },
    {
     "title": "$DataCore_Physical_Disks - Latency",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$tag_instance : Reads",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "DataCore_Physical_disk",
       "query": "SELECT derivative(\"TotalReads\", 1s) FROM \"DataCore_Physical_disk\" WHERE (\"instance\" =~ /^$DataCore_Physical_Disks$/) AND $timeFilter GROUP BY \"instance\"",
       "select": [
        [
         { "params": [ "TotalReadsTime" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" },
         {
          "params": [
           " /  derivative(\"TotalReads\", 1s)"
          ],
          "type": "math"
         }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Physical_Disks$/" }
       ]
      },
      {
       "alias": "$tag_instance : Writes",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "DataCore_Physical_disk",
       "query": "SELECT derivative(\"TotalWrites\", 1s) FROM \"DataCore_Physical_disk\" WHERE (\"instance\" =~ /^$DataCore_Physical_Disks$/) AND $timeFilter GROUP BY \"instance\"",
       "select": [
        [
         { "params": [ "TotalWritesTime" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" },
         {
          "params": [
           " / derivative(\"TotalWrites\", 1s)"
          ],
          "type": "math"
         }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Physical_Disks$/" }
       ]
      }
     ]
    },
    {
     "title": "$DataCore_Physical_Disks - IOPS",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "alias": "$tag_instance : Reads",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "DataCore_Physical_disk",
       "select": [
        [
         { "params": [ "TotalReads" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Physical_Disks$/" }
       ]
      },
      {
       "alias": "$tag_instance : Writes",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "DataCore_Physical_disk",
       "select": [
        [
         { "params": [ "TotalWrites" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Physical_Disks$/" }
       ]
      },
      {
       "alias": "$tag_instance : Total",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "DataCore_Physical_disk",
       "select": [
        [
         { "params": [ "TotalOperations" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Physical_Disks$/" }
       ]
      }
     ]
    },
    {
     "title": "$DataCore_Physical_Disks - Latency",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$tag_instance : Reads",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "DataCore_Physical_disk",
       "query": "SELECT derivative(\"TotalReads\", 1s) FROM \"DataCore_Physical_disk\" WHERE (\"instance\" =~ /^$DataCore_Physical_Disks$/) AND $timeFilter GROUP BY \"instance\"",
       "select": [
        [
         { "params": [ "TotalReadsTime" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" },
         {
          "params": [
           " /  derivative(\"TotalReads\", 1s)"
          ],
          "type": "math"
         }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Physical_Disks$/" }
       ]
      },
      {
       "alias": "$tag_instance : Writes",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "DataCore_Physical_disk",
       "query": "SELECT derivative(\"TotalWrites\", 1s) FROM \"DataCore_Physical_disk\" WHERE (\"instance\" =~ /^$DataCore_Physical_Disks$/) AND $timeFilter GROUP BY \"instance\"",
       "select": [
        [
         { "params": [ "TotalWritesTime" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" },
         {
          "params": [
           " / derivative(\"TotalWrites\", 1s)"
          ],
          "type": "math"
         }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Physical_Disks$/" }
       ]
      }
     ]
    },
    {
     "title": "$DataCore_Physical_Disks - IOPS",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "alias": "$tag_instance : Reads",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "DataCore_Physical_disk",
       "select": [
        [
         { "params": [ "TotalReads" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Physical_Disks$/" }
       ]
      },
      {
       "alias": "$tag_instance : Writes",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "DataCore_Physical_disk",
       "select": [
        [
         { "params": [ "TotalWrites" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Physical_Disks$/" }
       ]
      },
      {
       "alias": "$tag_instance : Total",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "DataCore_Physical_disk",
       "select": [
        [
         { "params": [ "TotalOperations" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Physical_Disks$/" }
       ]
      }
     ]
    },
    {
     "title": "$DataCore_Physical_Disks - Latency",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 32 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$tag_instance : Reads",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "DataCore_Physical_disk",
       "query": "SELECT derivative(\"TotalReads\", 1s) FROM \"DataCore_Physical_disk\" WHERE (\"instance\" =~ /^$DataCore_Physical_Disks$/) AND $timeFilter GROUP BY \"instance\"",
       "select": [
        [
         { "params": [ "TotalReadsTime" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" },
         {
          "params": [
           " /  derivative(\"TotalReads\", 1s)"
          ],
          "type": "math"
         }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Physical_Disks$/" }
       ]
      },
      {
       "alias": "$tag_instance : Writes",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "DataCore_Physical_disk",
       "query": "SELECT derivative(\"TotalWrites\", 1s) FROM \"DataCore_Physical_disk\" WHERE (\"instance\" =~ /^$DataCore_Physical_Disks$/) AND $timeFilter GROUP BY \"instance\"",
       "select": [
        [
         { "params": [ "TotalWritesTime" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" },
         {
          "params": [
           " / derivative(\"TotalWrites\", 1s)"
          ],
          "type": "math"
         }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_Physical_Disks$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "DataCore Server SCSI ports",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "$DataCore_SCSI_Ports - IOPS",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
     "repeat": "DataCore_SCSI_Ports",
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "alias": "$tag_instance : Reads",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "DataCore_SCSI_ports",
       "select": [
        [
         { "params": [ "TotalReads" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_SCSI_Ports$/" }
       ]
      },
      {
       "alias": "$tag_instance : Writes",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "DataCore_SCSI_ports",
       "select": [
        [
         { "params": [ "TotalWrites" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_SCSI_Ports$/" }
       ]
      },
      {
       "alias": "$tag_instance : Total",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "DataCore_SCSI_ports",
       "select": [
        [
         { "params": [ "TotalOperations" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_SCSI_Ports$/" }
       ]
      }
     ]
    },
    {
     "title": "$DataCore_SCSI_Ports - Latency",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
     "repeat": "DataCore_SCSI_Ports",
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$tag_instance : Reads",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "DataCore_SCSI_ports",
       "query": "SELECT derivative(\"TotalReads\", 1s) FROM \"DataCore_Physical_disk\" WHERE (\"instance\" =~ /^$DataCore_Physical_Disks$/) AND $timeFilter GROUP BY \"instance\"",
       "select": [
        [
         { "params": [ "TargetReadTime" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" },
         {
          "params": [
           " /  derivative(\"TargetReads\", 1s)"
          ],
          "type": "math"
         }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_SCSI_Ports$/" }
       ]
      },
      {
       "alias": "$tag_instance : Writes",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "DataCore_SCSI_ports",
       "query": "SELECT derivative(\"TotalWrites\", 1s) FROM \"DataCore_Physical_disk\" WHERE (\"instance\" =~ /^$DataCore_Physical_Disks$/) AND $timeFilter GROUP BY \"instance\"",
       "select": [
        [
         { "params": [ "TargetWriteTime" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" },
         {
          "params": [
           " / derivative(\"TargetWrites\", 1s)"
          ],
          "type": "math"
         }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_SCSI_Ports$/" }
       ]
      }
     ]
    },
    {
     "title": "$DataCore_SCSI_Ports - IOPS",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "alias": "$tag_instance : Reads",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "DataCore_SCSI_ports",
       "select": [
        [
         { "params": [ "TotalReads" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_SCSI_Ports$/" }
       ]
      },
      {
       "alias": "$tag_instance : Writes",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "DataCore_SCSI_ports",
       "select": [
        [
         { "params": [ "TotalWrites" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_SCSI_Ports$/" }
       ]
      },
      {
       "alias": "$tag_instance : Total",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "DataCore_SCSI_ports",
       "select": [
        [
         { "params": [ "TotalOperations" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_SCSI_Ports$/" }
       ]
      }
     ]
    },
    {
     "title": "$DataCore_SCSI_Ports - Latency",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$tag_instance : Reads",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "DataCore_SCSI_ports",
       "query": "SELECT derivative(\"TotalReads\", 1s) FROM \"DataCore_Physical_disk\" WHERE (\"instance\" =~ /^$DataCore_Physical_Disks$/) AND $timeFilter GROUP BY \"instance\"",
       "select": [
        [
         { "params": [ "TargetReadTime" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" },
         {
          "params": [
           " /  derivative(\"TargetReads\", 1s)"
          ],
          "type": "math"
         }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_SCSI_Ports$/" }
       ]
      },
      {
       "alias": "$tag_instance : Writes",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "DataCore_SCSI_ports",
       "query": "SELECT derivative(\"TotalWrites\", 1s) FROM \"DataCore_Physical_disk\" WHERE (\"instance\" =~ /^$DataCore_Physical_Disks$/) AND $timeFilter GROUP BY \"instance\"",
       "select": [
        [
         { "params": [ "TargetWriteTime" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" },
         {
          "params": [
           " / derivative(\"TargetWrites\", 1s)"
          ],
          "type": "math"
         }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_SCSI_Ports$/" }
       ]
      }
     ]
    },
    {
     "title": "$DataCore_SCSI_Ports - IOPS",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "alias": "$tag_instance : Reads",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "DataCore_SCSI_ports",
       "select": [
        [
         { "params": [ "TotalReads" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_SCSI_Ports$/" }
       ]
      },
      {
       "alias": "$tag_instance : Writes",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "DataCore_SCSI_ports",
       "select": [
        [
         { "params": [ "TotalWrites" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_SCSI_Ports$/" }
       ]
      },
      {
       "alias": "$tag_instance : Total",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "DataCore_SCSI_ports",
       "select": [
        [
         { "params": [ "TotalOperations" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_SCSI_Ports$/" }
       ]
      }
     ]
    },
    {
     "title": "$DataCore_SCSI_Ports - Latency",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$tag_instance : Reads",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "DataCore_SCSI_ports",
       "query": "SELECT derivative(\"TotalReads\", 1s) FROM \"DataCore_Physical_disk\" WHERE (\"instance\" =~ /^$DataCore_Physical_Disks$/) AND $timeFilter GROUP BY \"instance\"",
       "select": [
        [
         { "params": [ "TargetReadTime" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" },
         {
          "params": [
           " /  derivative(\"TargetReads\", 1s)"
          ],
          "type": "math"
         }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_SCSI_Ports$/" }
       ]
      },
      {
       "alias": "$tag_instance : Writes",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "DataCore_SCSI_ports",
       "query": "SELECT derivative(\"TotalWrites\", 1s) FROM \"DataCore_Physical_disk\" WHERE (\"instance\" =~ /^$DataCore_Physical_Disks$/) AND $timeFilter GROUP BY \"instance\"",
       "select": [
        [
         { "params": [ "TargetWriteTime" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" },
         {
          "params": [
           " / derivative(\"TargetWrites\", 1s)"
          ],
          "type": "math"
         }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_SCSI_Ports$/" }
       ]
      }
     ]
    },
    {
     "title": "$DataCore_SCSI_Ports - IOPS",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "alias": "$tag_instance : Reads",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "DataCore_SCSI_ports",
       "select": [
        [
         { "params": [ "TotalReads" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_SCSI_Ports$/" }
       ]
      },
      {
       "alias": "$tag_instance : Writes",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "DataCore_SCSI_ports",
       "select": [
        [
         { "params": [ "TotalWrites" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_SCSI_Ports$/" }
       ]
      },
      {
       "alias": "$tag_instance : Total",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "DataCore_SCSI_ports",
       "select": [
        [
         { "params": [ "TotalOperations" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_SCSI_Ports$/" }
       ]
      }
     ]
    },
    {
     "title": "$DataCore_SCSI_Ports - Latency",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$tag_instance : Reads",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "DataCore_SCSI_ports",
       "query": "SELECT derivative(\"TotalReads\", 1s) FROM \"DataCore_Physical_disk\" WHERE (\"instance\" =~ /^$DataCore_Physical_Disks$/) AND $timeFilter GROUP BY \"instance\"",
       "select": [
        [
         { "params": [ "TargetReadTime" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" },
         {
          "params": [
           " /  derivative(\"TargetReads\", 1s)"
          ],
          "type": "math"
         }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_SCSI_Ports$/" }
       ]
      },
      {
       "alias": "$tag_instance : Writes",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "DataCore_SCSI_ports",
       "query": "SELECT derivative(\"TotalWrites\", 1s) FROM \"DataCore_Physical_disk\" WHERE (\"instance\" =~ /^$DataCore_Physical_Disks$/) AND $timeFilter GROUP BY \"instance\"",
       "select": [
        [
         { "params": [ "TargetWriteTime" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" },
         {
          "params": [
           " / derivative(\"TargetWrites\", 1s)"
          ],
          "type": "math"
         }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_SCSI_Ports$/" }
       ]
      }
     ]
    },
    {
     "title": "$DataCore_SCSI_Ports - IOPS",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "alias": "$tag_instance : Reads",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "DataCore_SCSI_ports",
       "select": [
        [
         { "params": [ "TotalReads" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_SCSI_Ports$/" }
       ]
      },
      {
       "alias": "$tag_instance : Writes",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "DataCore_SCSI_ports",
       "select": [
        [
         { "params": [ "TotalWrites" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_SCSI_Ports$/" }
       ]
      },
      {
       "alias": "$tag_instance : Total",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "DataCore_SCSI_ports",
       "select": [
        [
         { "params": [ "TotalOperations" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_SCSI_Ports$/" }
       ]
      }
     ]
    },
    {
     "title": "$DataCore_SCSI_Ports - Latency",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 42 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$tag_instance : Reads",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "DataCore_SCSI_ports",
       "query": "SELECT derivative(\"TotalReads\", 1s) FROM \"DataCore_Physical_disk\" WHERE (\"instance\" =~ /^$DataCore_Physical_Disks$/) AND $timeFilter GROUP BY \"instance\"",
       "select": [
        [
         { "params": [ "TargetReadTime" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" },
         {
          "params": [
           " /  derivative(\"TargetReads\", 1s)"
          ],
          "type": "math"
         }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_SCSI_Ports$/" }
       ]
      },
      {
       "alias": "$tag_instance : Writes",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "DataCore_SCSI_ports",
       "query": "SELECT derivative(\"TotalWrites\", 1s) FROM \"DataCore_Physical_disk\" WHERE (\"instance\" =~ /^$DataCore_Physical_Disks$/) AND $timeFilter GROUP BY \"instance\"",
       "select": [
        [
         { "params": [ "TargetWriteTime" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" },
         {
          "params": [
           " / derivative(\"TargetWrites\", 1s)"
          ],
          "type": "math"
         }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_SCSI_Ports$/" }
       ]
      }
     ]
    },
    {
     "title": "$DataCore_SCSI_Ports - IOPS",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 51 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "alias": "$tag_instance : Reads",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "DataCore_SCSI_ports",
       "select": [
        [
         { "params": [ "TotalReads" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_SCSI_Ports$/" }
       ]
      },
      {
       "alias": "$tag_instance : Writes",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "DataCore_SCSI_ports",
       "select": [
        [
         { "params": [ "TotalWrites" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_SCSI_Ports$/" }
       ]
      },
      {
       "alias": "$tag_instance : Total",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "DataCore_SCSI_ports",
       "select": [
        [
         { "params": [ "TotalOperations" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_SCSI_Ports$/" }
       ]
      }
     ]
    },
    {
     "title": "$DataCore_SCSI_Ports - Latency",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 51 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$tag_instance : Reads",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "DataCore_SCSI_ports",
       "query": "SELECT derivative(\"TotalReads\", 1s) FROM \"DataCore_Physical_disk\" WHERE (\"instance\" =~ /^$DataCore_Physical_Disks$/) AND $timeFilter GROUP BY \"instance\"",
       "select": [
        [
         { "params": [ "TargetReadTime" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" },
         {
          "params": [
           " /  derivative(\"TargetReads\", 1s)"
          ],
          "type": "math"
         }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_SCSI_Ports$/" }
       ]
      },
      {
       "alias": "$tag_instance : Writes",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "DataCore_SCSI_ports",
       "query": "SELECT derivative(\"TotalWrites\", 1s) FROM \"DataCore_Physical_disk\" WHERE (\"instance\" =~ /^$DataCore_Physical_Disks$/) AND $timeFilter GROUP BY \"instance\"",
       "select": [
        [
         { "params": [ "TargetWriteTime" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" },
         {
          "params": [
           " / derivative(\"TargetWrites\", 1s)"
          ],
          "type": "math"
         }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_SCSI_Ports$/" }
       ]
      }
     ]
    },
    {
     "title": "$DataCore_SCSI_Ports - IOPS",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 60 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "alias": "$tag_instance : Reads",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "DataCore_SCSI_ports",
       "select": [
        [
         { "params": [ "TotalReads" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_SCSI_Ports$/" }
       ]
      },
      {
       "alias": "$tag_instance : Writes",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "DataCore_SCSI_ports",
       "select": [
        [
         { "params": [ "TotalWrites" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_SCSI_Ports$/" }
       ]
      },
      {
       "alias": "$tag_instance : Total",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "DataCore_SCSI_ports",
       "select": [
        [
         { "params": [ "TotalOperations" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_SCSI_Ports$/" }
       ]
      }
     ]
    },
    {
     "title": "$DataCore_SCSI_Ports - Latency",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 60 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$tag_instance : Reads",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "DataCore_SCSI_ports",
       "query": "SELECT derivative(\"TotalReads\", 1s) FROM \"DataCore_Physical_disk\" WHERE (\"instance\" =~ /^$DataCore_Physical_Disks$/) AND $timeFilter GROUP BY \"instance\"",
       "select": [
        [
         { "params": [ "TargetReadTime" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" },
         {
          "params": [
           " /  derivative(\"TargetReads\", 1s)"
          ],
          "type": "math"
         }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_SCSI_Ports$/" }
       ]
      },
      {
       "alias": "$tag_instance : Writes",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "DataCore_SCSI_ports",
       "query": "SELECT derivative(\"TotalWrites\", 1s) FROM \"DataCore_Physical_disk\" WHERE (\"instance\" =~ /^$DataCore_Physical_Disks$/) AND $timeFilter GROUP BY \"instance\"",
       "select": [
        [
         { "params": [ "TargetWriteTime" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" },
         {
          "params": [
           " / derivative(\"TargetWrites\", 1s)"
          ],
          "type": "math"
         }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_SCSI_Ports$/" }
       ]
      }
     ]
    },
    {
     "title": "$DataCore_SCSI_Ports - IOPS",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 69 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "alias": "$tag_instance : Reads",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "DataCore_SCSI_ports",
       "select": [
        [
         { "params": [ "TotalReads" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_SCSI_Ports$/" }
       ]
      },
      {
       "alias": "$tag_instance : Writes",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "DataCore_SCSI_ports",
       "select": [
        [
         { "params": [ "TotalWrites" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_SCSI_Ports$/" }
       ]
      },
      {
       "alias": "$tag_instance : Total",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "DataCore_SCSI_ports",
       "select": [
        [
         { "params": [ "TotalOperations" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_SCSI_Ports$/" }
       ]
      }
     ]
    },
    {
     "title": "$DataCore_SCSI_Ports - Latency",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 69 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$tag_instance : Reads",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "DataCore_SCSI_ports",
       "query": "SELECT derivative(\"TotalReads\", 1s) FROM \"DataCore_Physical_disk\" WHERE (\"instance\" =~ /^$DataCore_Physical_Disks$/) AND $timeFilter GROUP BY \"instance\"",
       "select": [
        [
         { "params": [ "TargetReadTime" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" },
         {
          "params": [
           " /  derivative(\"TargetReads\", 1s)"
          ],
          "type": "math"
         }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_SCSI_Ports$/" }
       ]
      },
      {
       "alias": "$tag_instance : Writes",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "DataCore_SCSI_ports",
       "query": "SELECT derivative(\"TotalWrites\", 1s) FROM \"DataCore_Physical_disk\" WHERE (\"instance\" =~ /^$DataCore_Physical_Disks$/) AND $timeFilter GROUP BY \"instance\"",
       "select": [
        [
         { "params": [ "TargetWriteTime" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" },
         {
          "params": [
           " / derivative(\"TargetWrites\", 1s)"
          ],
          "type": "math"
         }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_SCSI_Ports$/" }
       ]
      }
     ]
    },
    {
     "title": "$DataCore_SCSI_Ports - IOPS",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 78 },
     "yaxes": [
      { "format": "iops" }
     ],
     "targets": [
      {
       "alias": "$tag_instance : Reads",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "DataCore_SCSI_ports",
       "select": [
        [
         { "params": [ "TotalReads" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_SCSI_Ports$/" }
       ]
      },
      {
       "alias": "$tag_instance : Writes",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "DataCore_SCSI_ports",
       "select": [
        [
         { "params": [ "TotalWrites" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_SCSI_Ports$/" }
       ]
      },
      {
       "alias": "$tag_instance : Total",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "DataCore_SCSI_ports",
       "select": [
        [
         { "params": [ "TotalOperations" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_SCSI_Ports$/" }
       ]
      }
     ]
    },
    {
     "title": "$DataCore_SCSI_Ports - Latency",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 78 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$tag_instance : Reads",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "DataCore_SCSI_ports",
       "query": "SELECT derivative(\"TotalReads\", 1s) FROM \"DataCore_Physical_disk\" WHERE (\"instance\" =~ /^$DataCore_Physical_Disks$/) AND $timeFilter GROUP BY \"instance\"",
       "select": [
        [
         { "params": [ "TargetReadTime" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" },
         {
          "params": [
           " /  derivative(\"TargetReads\", 1s)"
          ],
          "type": "math"
         }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_SCSI_Ports$/" }
       ]
      },
      {
       "alias": "$tag_instance : Writes",
       "groupBy": [
        { "params": [ "instance" ], "type": "tag" }
       ],
       "measurement": "DataCore_SCSI_ports",
       "query": "SELECT derivative(\"TotalWrites\", 1s) FROM \"DataCore_Physical_disk\" WHERE (\"instance\" =~ /^$DataCore_Physical_Disks$/) AND $timeFilter GROUP BY \"instance\"",
       "select": [
        [
         { "params": [ "TargetWriteTime" ], "type": "field" },
         { "params": [ "1s" ], "type": "derivative" },
         {
          "params": [
           " / derivative(\"TargetWrites\", 1s)"
          ],
          "type": "math"
         }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$DataCore_SCSI_Ports$/" }
       ]
      }
     ]
    }
   ]
  }
 ]
}